name: 'Ticket in PR Title'
description: 'Github Action to Check if a JIRA Ticket is mentioned in the PR Title'
inputs:
  token:
    description: 'Github Token'
    required: true
  ticket-prefix:
    description: 'Ticket Prefix to search for'
    required: true
  fail:
    description: 'Whether to fail (default) or just warn'
    required: false
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'
